package com.vinsguru.order.common.enums;

public enum WorkflowAction {

    // payment
    PAYMENT_REQUEST_INITIATED,
    PAYMENT_PROCESSED,
    PAYMENT_DECLINED,
    PAYMENT_REFUND_INITIATED,

    // inventory
    INVENTORY_REQUEST_INITIATED,
    INVENTORY_DEDUCTED,
    INVENTORY_DECLINED,
    INVENTORY_RESTORE_INITIATED,

    // shipping
    SHIPPING_SCHEDULE_INITIATED,
    SHIPPING_SCHEDULED,
    SHIPPING_DECLINED

}
